// Copyright 2015 ThoughtWorks, Inc.

// This file is part of getgauge/html-report.

// getgauge/html-report is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// getgauge/html-report is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with getgauge/html-report.  If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"bytes"
	"encoding/json"
	"github.com/golang/protobuf/proto"
	"fmt"
	"github.com/getgauge/common"
	"gauge_messages"
	"io/ioutil"
	"log"
	"net"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"
)

const (
	reportTemplateDir           = "report-template"
	defaultReportsDir           = "reports"
	gaugeReportsDirEnvName      = "gauge_reports_dir" // directory where reports are generated by plugins
	overwriteReportsEnvProperty = "overwrite_reports"
	SETUP_ACTION                = "setup"
	EXECUTION_ACTION            = "execution"
	GAUGE_HOST                  = "localhost"
	GAUGE_PORT_ENV              = "plugin_connection_port"
	PLUGIN_ACTION_ENV           = "html-report_action"
)

var pluginProperties map[string]interface{}
var projectRoot string
var pluginDir string

func main() {
	projectRoot = os.Getenv(common.GaugeProjectRootEnv)
	if projectRoot == "" {
		fmt.Printf("Environment variable '%s' is not set. \n", common.GaugeProjectRootEnv)
		os.Exit(1)
	}

	var err error
	pluginDir, err = os.Getwd()
	if err != nil {
		fmt.Printf("Error finding current working directory: %s \n", err)
		os.Exit(1)
	}

	pluginPropertiesJson, readErr := ioutil.ReadFile("plugin.json")
	if readErr != nil {
		fmt.Printf("Could not read plugin.json: %s\n", readErr)
		os.Exit(1)
	}

	var pluginJson interface{}
	if err = json.Unmarshal([]byte(pluginPropertiesJson), &pluginJson); err != nil {
		fmt.Printf("Could not read plugin.json: %s\n", err)
		os.Exit(1)
	}
	pluginProperties = pluginJson.(map[string]interface{})

	action := os.Getenv(PLUGIN_ACTION_ENV)
	if action == SETUP_ACTION {
		addDefaultPropertiesToProject()
	} else if action == EXECUTION_ACTION {
		listener, err := NewGaugeListener(GAUGE_HOST, os.Getenv(GAUGE_PORT_ENV))
		if err != nil {
			fmt.Println("Could not create the gauge listener")
			os.Exit(1)
		}
		listener.OnSuiteResult(createReport)
		listener.Start()
	}
}

func addDefaultPropertiesToProject() {
	defaultPropertiesFile := getDefaultPropertiesFile()
	reportsDirProperty := &(common.Property{
		Comment:      "The path to the gauge reports directory. Should be either relative to the project directory or an absolute path",
		Name:         gaugeReportsDirEnvName,
		DefaultValue: defaultReportsDir})
	overwriteReportProperty := &(common.Property{
		Comment:      "Set as false if gauge reports should not be overwritten on each execution. A new time-stamped directory will be created on each execution.",
		Name:         overwriteReportsEnvProperty,
		DefaultValue: "true"})

	if !common.FileExists(defaultPropertiesFile) {
		fmt.Printf("Failed to setup html report plugin in project. Default properties file does not exist at %s. \n", defaultPropertiesFile)
		return
	}
	if err := common.AppendProperties(defaultPropertiesFile, reportsDirProperty, overwriteReportProperty); err != nil {
		fmt.Printf("Failed to setup html report plugin in project: %s \n", err)
		return
	}
	fmt.Println("Succesfully added configurations for html-report to env/default/default.properties")
}

func getDefaultPropertiesFile() string {
	return filepath.Join(projectRoot, "env", "default", "default.properties")
}

type GaugeResultHandlerFn func(*gauge_messages.SuiteExecutionResult)

type GaugeListener struct {
	connection      net.Conn
	onResultHandler GaugeResultHandlerFn
}

func NewGaugeListener(host string, port string) (*GaugeListener, error) {
	conn, err := net.Dial("tcp", fmt.Sprintf("%s:%s", host, port))
	if err == nil {
		return &GaugeListener{connection: conn}, nil
	} else {
		return nil, err
	}
}

func (gaugeListener *GaugeListener) OnSuiteResult(resultHandler GaugeResultHandlerFn) {
	gaugeListener.onResultHandler = resultHandler
}

func (gaugeListener *GaugeListener) Start() {
	buffer := new(bytes.Buffer)
	data := make([]byte, 8192)
	for {
		n, err := gaugeListener.connection.Read(data)
		if err != nil {
			return
		}
		buffer.Write(data[0:n])
		gaugeListener.processMessages(buffer)
	}
}

func (gaugeListener *GaugeListener) processMessages(buffer *bytes.Buffer) {
	for {
		messageLength, bytesRead := proto.DecodeVarint(buffer.Bytes())
		if messageLength > 0 && messageLength < uint64(buffer.Len()) {
			message := &gauge_messages.Message{}
			messageBoundary := int(messageLength) + bytesRead
			err := proto.Unmarshal(buffer.Bytes()[bytesRead:messageBoundary], message)
			if err != nil {
				log.Printf("Failed to read proto message: %s\n", err.Error())
			} else {
				if *message.MessageType == gauge_messages.Message_KillProcessRequest {
					os.Exit(0)
				}
				if *message.MessageType == gauge_messages.Message_SuiteExecutionResult {
					result := message.GetSuiteExecutionResult()
					gaugeListener.onResultHandler(result)
					gaugeListener.connection.Close()
				}
				buffer.Next(messageBoundary)
				if buffer.Len() == 0 {
					return
				}
			}
		} else {
			return
		}
	}
}

func createReport(suiteResult *gauge_messages.SuiteExecutionResult) {
	os.Chdir(projectRoot)
	contents := generateJsFileContents(suiteResult)
	reportsDir, err := filepath.Abs(os.Getenv(gaugeReportsDirEnvName))
	if reportsDir == "" || err != nil {
		createDirectory(defaultReportsDir)
		reportsDir = defaultReportsDir
	} else {
		createDirectory(reportsDir)
	}

	var currentReportDir string
	if shouldOverwriteReports() {
		currentReportDir = path.Join(reportsDir, "html-report")
	} else {
		currentReportDir = path.Join(reportsDir, "html-report", time.Now().Format("2006-01-02 15:04:05"))
	}
	createDirectory(currentReportDir)
	copyReportTemplateFiles(currentReportDir)

	resultJsPath := path.Join(currentReportDir, "js", "result.js")
	err = ioutil.WriteFile(resultJsPath, contents, common.NewFilePermissions)
	if err != nil {
		fmt.Printf("Error writing file %s :%s\n", resultJsPath, err)
	}
	fmt.Printf("Sucessfully generated html reports to => %s\n", currentReportDir)
}

func copyReportTemplateFiles(reportDir string) {
	reportTemplateDir := path.Join(pluginDir, reportTemplateDir)
	err := common.MirrorDir(reportTemplateDir, reportDir)
	if err != nil {
		fmt.Printf("Error copying template directory :%s\n", err)
		os.Exit(1)
	}
}

func shouldOverwriteReports() bool {
	envValue := os.Getenv(overwriteReportsEnvProperty)
	if strings.ToLower(envValue) == "true" {
		return true
	}
	return false
}

func generateJsFileContents(suiteResult *gauge_messages.SuiteExecutionResult) []byte {
	var buffer bytes.Buffer
	executionResultJson := marshal(suiteResult)
	itemsTypeJson := marshal(convertKeysToString(gauge_messages.ProtoItem_ItemType_name))
	parameterTypeJson := marshal(convertKeysToString(gauge_messages.Parameter_ParameterType_name))
	fragmentTypeJson := marshal(convertKeysToString(gauge_messages.Fragment_FragmentType_name))

	buffer.WriteString("var gaugeExecutionResult = ")
	buffer.Write(executionResultJson)
	buffer.WriteString(";")
	buffer.WriteString("\n var itemTypesMap = ")
	buffer.Write(itemsTypeJson)
	buffer.WriteString(";")
	buffer.WriteString("\n var parameterTypesMap = ")
	buffer.Write(parameterTypeJson)
	buffer.WriteString(";")
	buffer.WriteString("\n var fragmentTypesMap = ")
	buffer.Write(fragmentTypeJson)
	buffer.WriteString(";")

	return buffer.Bytes()
}

func convertKeysToString(intKeyMap map[int32]string) map[string]string {
	stringKeyMap := make(map[string]string, 0)
	for key, val := range intKeyMap {
		stringKeyMap[fmt.Sprintf("%d", key)] = val
	}
	return stringKeyMap
}

func marshal(item interface{}) []byte {
	marshalledResult, err := json.Marshal(item)
	if err != nil {
		fmt.Printf("Failed to convert to json :%s\n", err)
		os.Exit(1)
	}
	return marshalledResult
}

func createDirectory(dir string) {
	if common.DirExists(dir) {
		return
	}
	if err := os.MkdirAll(dir, common.NewDirectoryPermissions); err != nil {
		fmt.Printf("Failed to create directory %s: %s\n", defaultReportsDir, err)
		os.Exit(1)
	}
}
