// Copyright 2015 ThoughtWorks, Inc.

// This file is part of getgauge/html-report.

// getgauge/html-report is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// getgauge/html-report is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with getgauge/html-report.  If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/getgauge/common"
	"github.com/getgauge/html-report/gauge_messages"
	"github.com/getgauge/html-report/listener"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	reportTemplateDir           = "report-template"
	defaultReportsDir           = "reports"
	gaugeReportsDirEnvName      = "gauge_reports_dir" // directory where reports are generated by plugins
	overwriteReportsEnvProperty = "overwrite_reports"
	resultJsFile                = "result.js"
	htmlReport                  = "html-report"
	SETUP_ACTION                = "setup"
	EXECUTION_ACTION            = "execution"
	GAUGE_HOST                  = "localhost"
	GAUGE_PORT_ENV              = "plugin_connection_port"
	PLUGIN_ACTION_ENV           = "html-report_action"
	timeFormat                  = "2006-01-02 15.04.05"
)

var projectRoot string
var pluginDir string

type nameGenerator interface {
	randomName() string
}

type timeStampedNameGenerator struct {
}

func (T timeStampedNameGenerator) randomName() string {
	return time.Now().Format(timeFormat)
}

func findPluginAndProjectRoot() {
	projectRoot = os.Getenv(common.GaugeProjectRootEnv)
	if projectRoot == "" {
		fmt.Println("Environment variable '%s' is not set.", common.GaugeProjectRootEnv)
		os.Exit(1)
	}

	var err error
	pluginDir, err = os.Getwd()
	if err != nil {
		fmt.Println("Error finding current working directory: %s", err)
		os.Exit(1)
	}
}

func createExecutionReport() {
	os.Chdir(projectRoot)
	listener, err := listener.NewGaugeListener(GAUGE_HOST, os.Getenv(GAUGE_PORT_ENV))
	if err != nil {
		fmt.Println("Could not create the gauge listener")
		os.Exit(1)
	}
	listener.OnSuiteResult(createReport)
	listener.Start()
}

func addDefaultPropertiesToProject() {
	defaultPropertiesFile := getDefaultPropertiesFile()

	reportsDirProperty := &(common.Property{
		Comment:      "The path to the gauge reports directory. Should be either relative to the project directory or an absolute path",
		Name:         gaugeReportsDirEnvName,
		DefaultValue: defaultReportsDir})

	overwriteReportProperty := &(common.Property{
		Comment:      "Set as false if gauge reports should not be overwritten on each execution. A new time-stamped directory will be created on each execution.",
		Name:         overwriteReportsEnvProperty,
		DefaultValue: "true"})

	if !common.FileExists(defaultPropertiesFile) {
		fmt.Println("Failed to setup html report plugin in project. Default properties file does not exist at %s.", defaultPropertiesFile)
		return
	}
	if err := common.AppendProperties(defaultPropertiesFile, reportsDirProperty, overwriteReportProperty); err != nil {
		fmt.Println("Failed to setup html report plugin in project: %s", err)
		return
	}
	fmt.Println("Succesfully added configurations for html-report to env/default/default.properties")
}

func getDefaultPropertiesFile() string {
	return filepath.Join(projectRoot, "env", "default", "default.properties")
}

func createReport(suiteResult *gauge_messages.SuiteExecutionResult) {
	jsContents := generateJsFileContents(suiteResult)
	reportDir, err := createHtmlReport(createReportsDirectory(), jsContents, getNameGen())
	if err != nil {
		fmt.Println("Report generation failed: %s", err)
		os.Exit(1)
	} else {
		fmt.Println("Successfully generated html-report to => %s", reportDir)
	}

}

func getNameGen() nameGenerator {
	var nameGen nameGenerator
	if shouldOverwriteReports() {
		nameGen = nil
	} else {
		nameGen = timeStampedNameGenerator{}
	}
	return nameGen
}

func createHtmlReport(reportsDir string, jsContents []byte, nameGen nameGenerator) (string, error) {
	var currentReportDir string
	if nameGen != nil {
		currentReportDir = filepath.Join(reportsDir, htmlReport, nameGen.randomName())
	} else {
		currentReportDir = filepath.Join(reportsDir, htmlReport)
	}
	createDirectory(currentReportDir)
	err := copyReportTemplateFiles(currentReportDir)
	if err != nil {
		return "", errors.New(fmt.Sprintln("Error copying template directory :%s", err))
	}
	return currentReportDir, writeResultJsFile(currentReportDir, jsContents)
}

func createReportsDirectory() string {
	reportsDir, err := filepath.Abs(os.Getenv(gaugeReportsDirEnvName))
	if reportsDir == "" || err != nil {
		reportsDir = defaultReportsDir
	}
	createDirectory(reportsDir)
	return reportsDir
}

func copyReportTemplateFiles(reportDir string) error {
	reportTemplateDir := filepath.Join(pluginDir, reportTemplateDir)
	_, err := common.MirrorDir(reportTemplateDir, reportDir)
	return err
}

func writeResultJsFile(reportDir string, jsContents []byte) error {
	resultJsPath := filepath.Join(reportDir, "js", resultJsFile)
	err := ioutil.WriteFile(resultJsPath, jsContents, common.NewFilePermissions)
	if err != nil {
		return errors.New(fmt.Sprintln("Failed to copy file: %s %s", resultJsFile, err))
	}
	return nil
}

func shouldOverwriteReports() bool {
	envValue := os.Getenv(overwriteReportsEnvProperty)
	if strings.ToLower(envValue) == "true" {
		return true
	}
	return false
}

func generateJsFileContents(suiteResult *gauge_messages.SuiteExecutionResult) []byte {
	var buffer bytes.Buffer
	executionResultJson := marshal(suiteResult)
	itemsTypeJson := marshal(convertKeysToString(gauge_messages.ProtoItem_ItemType_name))
	parameterTypeJson := marshal(convertKeysToString(gauge_messages.Parameter_ParameterType_name))
	fragmentTypeJson := marshal(convertKeysToString(gauge_messages.Fragment_FragmentType_name))

	buffer.WriteString("var gaugeExecutionResult = ")
	buffer.Write(executionResultJson)
	buffer.WriteString(";")
	buffer.WriteString("\n var itemTypesMap = ")
	buffer.Write(itemsTypeJson)
	buffer.WriteString(";")
	buffer.WriteString("\n var parameterTypesMap = ")
	buffer.Write(parameterTypeJson)
	buffer.WriteString(";")
	buffer.WriteString("\n var fragmentTypesMap = ")
	buffer.Write(fragmentTypeJson)
	buffer.WriteString(";")

	return buffer.Bytes()
}

func convertKeysToString(intKeyMap map[int32]string) map[string]string {
	stringKeyMap := make(map[string]string, 0)
	for key, val := range intKeyMap {
		stringKeyMap[fmt.Sprintf("%d", key)] = val
	}
	return stringKeyMap
}

func marshal(item interface{}) []byte {
	marshalledResult, err := json.Marshal(item)
	if err != nil {
		fmt.Println("Failed to convert to json :%s", err)
		os.Exit(1)
	}
	return marshalledResult
}

func createDirectory(dir string) {
	if common.DirExists(dir) {
		return
	}
	if err := os.MkdirAll(dir, common.NewDirectoryPermissions); err != nil {
		fmt.Println("Failed to create directory %s: %s", defaultReportsDir, err)
		os.Exit(1)
	}
}
