name: HTML Report

on: [push, pull_request]

jobs:
  test:
    name: Go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.13.1]
        os: [ubuntu-latest, macos-latest]

    steps:

      - uses: actions/checkout@v1
        with:
          path: src/github.com/getgauge/html-report

      - name: Setup go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Download packages
        run: |
          export GOPATH=`cd ../../../../ && pwd`
          go get -t -v ./...

      - name: Run tests
        run: |
          export GOPATH=`cd ../../../../ && pwd`
          go test ./...

      - name: Build and Install
        run: |
          export GOPATH=`cd ../../../../ && pwd`
          go run build/make.go
          go run build/make.go --install


