name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Go ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - uses: actions/checkout@v3

      - name: Setup go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Download packages
        run: |
          go get -t -v ./...

      - name: Run tests
        run: |
          go test ./...

      - name: Build and Install
        run: |
          go run build/make.go
          go run build/make.go --install


